Added mdanse_job application for running a job through a stand-alone dialog
ISISNeutronMuon/MDANSE pull request #65
Opened 2022-04-20 11:34 UTC by eurydice76

See issue #62 for details

2022-04-20 12:10 UTC, RastislavTuranyi requested changes
The script works well, but I believe improving the information given by -h to be very useful.

Other than that, I am not sure how the changes to Doc are related to this script.

2022-04-20 12:10 UTC, RastislavTuranyi commented on Doc/conf_api.py
> +extensions = ['sphinx.ext.autodoc', 'sphinx.ext.viewcode', 'sphinx.ext.graphviz', 'sphinx.ext.inheritance_diagram''sphinx.ext.pngmath' if minor <= 6 else 'sphinx.ext.imgmath']
I think you are missing a comma here. Regardless, your changes caused a lot of warnings that it cannot create inheritance diagrams when running `build_api`.

2022-04-20 12:33 UTC, eurydice76 commented
Thanks for the comments. I added more info to the `mdanse_job` script help. Is it OK for you now ? For the fix in the 
documentation, you are fully right I should have done this in a separate branch/PR. I can do it if you want

2022-04-20 12:52 UTC, RastislavTuranyi reviewed
I think it would be best make the changes to Doc in a separate branch and PR, so that we can discuss them separately. 

Thank you for making the usage of the script easier. I would say that currently just running -h gives enough info for users to be able to use the script.

2022-04-20 13:08 UTC, eurydice76 commented
OK, let's create another PR for the doc changes

2022-04-28 15:52 UTC, sanghamitra-mukhopadhyay commented
Can we resolve the conflict ?

2022-04-28 15:54 UTC, sanghamitra-mukhopadhyay approved these changes

2022-04-28 16:03 UTC, eurydice76 commented
The functional tests are failing. So it becomes urgent for the branch #66 #56 and  to me merged.

2022-04-28 16:29 UTC, sanghamitra-mukhopadhyay commented
I see a conflict in #66 and #56/ #59 are still in work in progress?

2022-05-03 16:40 UTC, merged